# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef89194c01782ff8f8c03d5e-shop-secret"
name = "Remix app"
handle = "remix-app"
application_url = "https://05dd-122-180-85-113.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a57e30fb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_customers,read_orders,read_products,read_themes,write_customers,write_orders,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://1eb1-122-180-85-113.ngrok-free.app/auth/callback",
  "https://1eb1-122-180-85-113.ngrok-free.app/auth/shopify/callback",
  "https://1eb1-122-180-85-113.ngrok-free.app/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "https://3fb0-122-180-85-113.ngrok-free.app/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "https://3fb0-122-180-85-113.ngrok-free.app/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "https://3fb0-122-180-85-113.ngrok-free.app/webhooks/shop/redact"


[pos]
embedded = false
